version: '3.5'

services:
  # --- БАЗА ДАННЫХ (MySQL 8) ---
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    networks:
      - zbx_net
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: zabbix
      MYSQL_DATABASE: zabbixdb
      MYSQL_PASSWORD: PasswOrd
      MYSQL_ROOT_PASSWORD: StrongPassword
    volumes:
      - ./zabbix-data/mysql:/var/lib/mysql
    restart: unless-stopped

  # --- ZABBIX SERVER (Версия 7.4) ---
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-7.4-latest
    container_name: zabbix-server-mysql
    networks:
      - zbx_net
    ports:
      - 10051:10051
    volumes:
      - ./zabbix-data/alertscripts:/usr/lib/zabbix/alertscripts
      - ./zabbix-data/externalscripts:/usr/lib/zabbix/externalscripts
      - ./zabbix-data/export:/var/lib/zabbix/export
      - ./zabbix-data/modules:/var/lib/zabbix/modules
      - ./zabbix-data/enc:/var/lib/zabbix/enc
      - ./zabbix-data/ssh_keys:/var/lib/zabbix/ssh_keys
      - ./zabbix-data/mibs:/var/lib/zabbix/mibs
      - ./zabbix-data/snmptraps:/var/lib/zabbix/snmptraps
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbixdb
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=PasswOrd
      - MYSQL_ROOT_PASSWORD=StrongPassword
      - ZBX_SERVERNAME=Zabbix Server
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
    depends_on:
      - mysql-server
    restart: unless-stopped

  # --- ZABBIX WEB (Версия 7.4) ---
  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.4-latest
    container_name: zabbix-web-nginx-mysql
    networks:
      - zbx_net
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./zabbix-nginx/nginx:/etc/ssl/nginx
      - ./zabbix-nginx/modules/:/usr/share/zabbix/modules/
    environment:
      - ZBX_SERVER_HOST=zabbix-server-mysql
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbixdb
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=PasswOrd
      - MYSQL_ROOT_PASSWORD=StrongPassword
      - PHP_TIMEZONE=Etc/UTC
    depends_on:
      - mysql-server
      - zabbix-server-mysql
    restart: unless-stopped

  # --- ZABBIX JAVA GATEWAY ---
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-7.4-latest
    container_name: zabbix-java-gateway
    networks:
      - zbx_net
    ports:
      - 10052:10052
    restart: unless-stopped

  # --- ZABBIX AGENT (Мониторинг физического сервера) ---
  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-7.4-latest
    container_name: zabbix-agent
    networks:
      - zbx_net
    volumes:
      - /:/host:ro
      - /var/log:/var/log:ro
    environment:
      - ZBX_SERVER_HOST=zabbix-server-mysql
      - ZBX_HOSTNAME=Linux-Server-Monitor
    privileged: true
    restart: unless-stopped

networks:
  zbx_net:
    driver: bridge
